### ISSUE TITLE
Reference Error

### ISSUE THREAD

**Issue by ElSuccerro** [Smirnov75/ComfyUI-mxToolkit#17]
Hi, i got the following bug if i load an workflow with an Slider 2D Node:

Loading aborted due to error reloading workflow data

ReferenceError: clamp is not defined
ReferenceError: clamp is not defined
    at MXSlider2D.node.onPropertyChanged (http://127.0.0.1:8188/extensions/ComfyUI-mxToolkit/Slider2D.js:60:18)
    at MXSlider2D.node.onConfigure (http://127.0.0.1:8188/extensions/ComfyUI-mxToolkit/Slider2D.js:35:18)
    at LGraphNode.configure (http://127.0.0.1:8188/assets/index-ipA15YlU.js:1127:27621)
    at _a5.configure (http://127.0.0.1:8188/assets/index-ipA15YlU.js:1127:23325)
    at LGraph.configure (http://127.0.0.1:8188/assets/index-ipA15YlU.js:1438:9750)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:14:29)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:160:21)
    at _ComfyApp.<anonymous> (http://127.0.0.1:8188/assets/index-ipA15YlU.js:1436:49810)
    at Generator.next (<anonymous>)
    at fulfilled (http://127.0.0.1:8188/assets/index-ipA15YlU.js:2:2229)
This may be due to the following script:
/extensions/ComfyUI-mxToolkit/Slider2D.js

I run ComfyUI: 2532[39fb74](2024-08-13) Windows Standalone

**Comment by xthedarknight99x** [comment]
Commenting to report the same issue 

ComfyUI: 2532[39fb74](2024-08-13)
Manager: V2.48.6

If I disable the ComfyUI-MxTookit Node the issue goes away.

![Slider js error](https://github.com/user-attachments/assets/a25f5943-d977-43cf-ba91-87dc42c240f0)

**Comment by ElSuccerro** [comment]
Thanks for fixing!

**Comment by xthedarknight99x** [comment]
Thank you!
