### ISSUE TITLE
Slider UI appearance issue

### ISSUE THREAD

**Issue by Spinaster** [Smirnov75/ComfyUI-mxToolkit#21]
Hello, as you can see in the picture attached, the nodes UI it's completely different from the one showed in the examples.
Any suggestions?
Thank you.

![Screenshot 2024-09-16 153622](https://github.com/user-attachments/assets/63e784e4-d21f-4384-a35d-bcea4bb8ba09)

**Comment by Smirnov75** [comment]
I have tested the nodes with the latest version of ComfyUI. Everything works correctly.
Which version of ComfyUI are you using, and how do you install the nodes?

**Comment by Spinaster** [comment]
I'm using the latest version of Comfy and I installed via Manger.

**Comment by n0valis** [comment]
Same for me. ComfyUI v0.2.2 installed via Manager

**Comment by Atreia5710** [comment]
Do you have any messages in the browser console?
To launch ComfyUI, press "Ctrl+ Shift + J" to open the browser console, then create a "Slider" and "MxReroute" node. If you have any new messages/errors, please let us know.
If "Ctrl + Shift + J" does't work, press F12 and select "Console".

**Comment by n0valis** [comment]
I am not sure why I got this problem but after I checked on a fresh workspace I could not recreate the issue, so I guess I'm fine.
I got an error message though for a a slider, I'm not sure if it is of any concern I couldn't test it further. I connected a Slider to the steps value in KSampler. It says: 
`Uncaught TypeError: this.updateThisNodeGraph is not a function
    at MXSlider.node.onMouseMove (Slider.js:137:18)
    at __LGraphCanvas.processMouseMove (litegraph.es.js:5994:18)
    at LGraphCanvas.processMouseMove (simpleTouchSupport.ts:110:27)
    at LGraphCanvas.processMouseMove (app.ts:1240:9)`

At last I want to mention that I still cannot find the reroute node in mxToolkit, there are only four nodes: Slider, Slider 2D, Stop and Seed. Where is the reroute supposed to be?

**Comment by Atreia5710** [comment]
> At last I want to mention that I still cannot find the reroute node in mxToolkit, there are only four nodes: Slider, Slider 2D, Stop and Seed. Where is the reroute supposed to be?

RMB -> Add Node -> utils -> mxReroute

**Comment by PGCRT** [comment]
ComfyUI: v0.3.7-1-g1e21f4c
         (2024-12-05)
Manager: V2.55.3

![2024-12-06 00_48_29-_CRT_FLUX SUPER (v2 10) (2) - ComfyUI](https://github.com/user-attachments/assets/3adef024-518e-4536-8c42-b33427848de8)

**Comment by Smirnov75** [comment]
It seems that your mxToolkit is not updated to the latest version - 0.9.7

**Comment by PGCRT** [comment]
It is unfortunately, I also tried to uninstall and reinstall, didn't fix the issue, this is a very usefull node and I'm using it for a while sadly

**Comment by PGCRT** [comment]
https://github.com/user-attachments/assets/7a836c4a-5ea1-4313-bef6-69014af630c8

**Comment by Smirnov75** [comment]
In the latest version of mxToolkit, the method for hiding these widgets has changed to align with updates in ComfyUI. Therefore, to ensure proper functionality, it is necessary to use the latest versions of both ComfyUI and mxToolkit.

Check the version directly by opening the file ComfyUI\custom_nodes\ComfyUI-mxToolkit\js\Slider.js
Also, take a look at this line:
https://github.com/Smirnov75/ComfyUI-mxToolkit/blob/66be54a3d5204b28bb40a94be1a01e74bcf28c23/js/Slider.js#L25

I just downloaded and performed a clean installation of the latest portable version of ComfyUI (0.3.7 windows), as well as installed mxToolkit via the Manager – everything is displaying correctly.

**Comment by PGCRT** [comment]
I have this version
        for (let i=0; i<3; i++) this.node.widgets[i].hidden = true;
this is up to date, as well as comfyUI 

-ComfyUI: v0.3.7-4-g93477f8
         (2024-12-06)
Manager: V2.55.4

I will try to reinstall eveything from the beginning

**Comment by Smirnov75** [comment]
Unfortunately, I was unable to reproduce this issue. Nevertheless, I have decided to use both the old and the new method for hiding widgets. I believe that using them simultaneously will not cause any problems.
The nodes have been updated to version 0.9.8.

**Comment by PGCRT** [comment]
I updated, and yes this is properly displayed now, thank you 
![2024-12-08 18_29_31-_CRT_FLUX SUPER REDUX (v2 10) (2) - ComfyUI](https://github.com/user-attachments/assets/0231e647-4435-4274-959f-218bdb582bf7)
